### ISSUE TITLE
Track LICENSE and NOTICE issues for `incubator-openwhisk-runtime-swift`

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-release#100]
Please use this issue to track any issues surrounding either the [LICENSE.txt](https://github.com/apache/incubator-openwhisk-runtime-swift/blob/master/LICENSE.txt) or [NOTICE.txt](https://github.com/apache/incubator-openwhisk-runtime-swift/blob/master/NOTICE.txt) file for the associated repository listed in the title.

**Open Issues/PRs**:
- _None_

**Closed Issues/Merged PRs**:
- PR [#27 - Add the NOTICE file](https://github.com/apache/incubator-openwhisk-runtime-swift/pull/27)
- PR [#28 - Add license headers](https://github.com/apache/incubator-openwhisk-runtime-swift/pull/28)
- PR [#43 - update NOTICE file](https://github.com/apache/incubator-openwhisk-runtime-swift/pull/43)
    - issue [#85 - Review NOTICE file for incubator-openwhisk-runtime-swift](https://github.com/apache/incubator-openwhisk-release/issues/85)
- PR [#44 - Add the licenses of dependencies into LICENSE file](https://github.com/apache/incubator-openwhisk-runtime-swift/pull/44)
- PR [#46 - Add scancode using ASF config. to Travis build](https://github.com/apache/incubator-openwhisk-runtime-swift/pull/46)
- PR [#48 - Add license headers](https://github.com/apache/incubator-openwhisk-runtime-swift/pull/48)
    - [#31 - Some source files miss Apache license headers](https://github.com/apache/incubator-openwhisk-runtime-swift/issues/31)
- PR [#51 - Update .md and .sh files to pass scancode with latest .cfg](https://github.com/apache/incubator-openwhisk-runtime-swift/pull/51)
- PR [#54 - Remove IBM copyright from 3 files](https://github.com/apache/incubator-openwhisk-runtime-swift/pull/54)
- PR [#55 - Add ASF license headers to all Scala .conf files.](https://github.com/apache/incubator-openwhisk-runtime-swift/pull/55)
- PR [#57 - Fix markdown files with a typo. in the Hash license header](https://github.com/apache/incubator-openwhisk-runtime-swift/pull/57)
- PR [#58  - Restore the LICENSE and NOTICE to fit the source code release](https://github.com/apache/incubator-openwhisk-runtime-swift/pull/58)
- PR [#61 -  Fix travis yaml file asf header, change to mini](https://github.com/apache/incubator-openwhisk-runtime-swift/pull/61)
- PR [#62 - Add headers to build.gradle and settings.gradle](https://github.com/apache/incubator-openwhisk-runtime-swift/pull/62)
- PR [#63 - Last files to need ASF License headers](https://github.com/apache/incubator-openwhisk-runtime-swift/pull/63)
- PR [#64 - Fix bad Dockerfile license and use ASF release config](https://github.com/apache/incubator-openwhisk-runtime-swift/pull/64)

**Closed Issues/PRs**
- [#156 - Swift runtime has "SPM" builds (binaries) using ext. code with no license attributio](https://github.com/apache/incubator-openwhisk-release/issues/156)
    - Carlos reviewed and recommended "close".
- [#52 - Rename "license" subdir. to "licenses" to conform to other project repos.](https://github.com/apache/incubator-openwhisk-runtime-swift/issues/52)
    - _Not applicable to source code release_
 
**Related Issues**
- [#170 - Change directory from 'license' to 'licenses' for runtime-swift](https://github.com/apache/incubator-openwhisk-release/issues/170)

**Comment by daisy-ycguo** [comment]
An issue is opened to track the header issue: https://github.com/apache/incubator-openwhisk-runtime-swift/issues/31

**Comment by daisy-ycguo** [comment]
I suggest to exclude below file from header checking because it's a package configuration file.
```
openwhisk-runtime-swift/tests/dat/actions/SwiftyRequest/Package.resolved
```

**Comment by daisy-ycguo** [comment]
A PR is created: https://github.com/apache/incubator-openwhisk-runtime-swift/pull/48

**Comment by mrutkows** [comment]
@daisy-ycguo merged https://github.com/apache/incubator-openwhisk-runtime-swift/pull/48
