### ISSUE TITLE
Track LICENSE and NOTICE issues for `incubator-openwhisk-runtime-docker`

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-release#101]
Please use this issue to track any issues surrounding either the [LICENSE.txt](https://github.com/apache/incubator-openwhisk-runtime-docker/blob/master/LICENSE.txt) or [NOTICE.txt](https://github.com/apache/incubator-openwhisk-runtime-doscker/blob/master/NOTICE.txt) file for the associated repository listed in the title.

**Open Issues/PRs**:
- _None_

**Closed Issues/Merged PRs**:
- PR [#18 - Add the NOTICE file](https://github.com/apache/incubator-openwhisk-runtime-docker/pull/18)
- PR [#25 - update notice file](https://github.com/apache/incubator-openwhisk-runtime-docker/pull/25)
    - Issue [#80 - Review NOTICE file for incubator-openwhisk-runtime-docker](https://github.com/apache/incubator-openwhisk-release/issues/80)
- PR [#27 - Add license headers](https://github.com/apache/incubator-openwhisk-runtime-docker/pull/27)
    - Issue [#19 - Add the license headers](https://github.com/apache/incubator-openwhisk-runtime-docker/pull/19)
    - Issue [#20 - Some source files miss Apache license headers](https://github.com/apache/incubator-openwhisk-runtime-docker/issues/20)
- PR [#28 - Add the licenses of the dependencies into LICENSE](https://github.com/apache/incubator-openwhisk-runtime-docker/pull/28)
- PR [#29 - Add scancode using ASF config. to Travis build](https://github.com/apache/incubator-openwhisk-runtime-docker/pull/29)
- PR [#32 - Update .md and .sh files to pass scancode with latest .cfg](https://github.com/apache/incubator-openwhisk-runtime-docker/pull/32)
- PR [#33 - Add ASF license headers to all Scala .conf files](https://github.com/apache/incubator-openwhisk-runtime-docker/pull/33)
- PR [#36 - Fix markdown files with a typo. in the Hash license header](https://github.com/apache/incubator-openwhisk-runtime-docker/pull/36)
- PR [#37 - Restore the LICENSE and NOTICE to fit the source code release](https://github.com/apache/incubator-openwhisk-runtime-docker/pull/37)
- PR [#38 - Fix travis yaml file asf header, change to mini.](https://github.com/apache/incubator-openwhisk-runtime-docker/pull/38)
- PR [#39 -  Last files to need ASF License headers.](https://github.com/apache/incubator-openwhisk-runtime-docker/pull/39)
- PI [#40 - Fix example.c to have correct ASF license header](https://github.com/apache/incubator-openwhisk-runtime-docker/pull/40)
- PR [#41 - Fix bad Dockerfile license and use ASF release config](https://github.com/apache/incubator-openwhisk-runtime-docker/pull/41)

**Comment by daisy-ycguo** [comment]
An issue is opened to track the missing headers: https://github.com/apache/incubator-openwhisk-runtime-docker/issues/20

**Comment by daisy-ycguo** [comment]
A PR https://github.com/apache/incubator-openwhisk-runtime-docker/pull/27 is merged. The license header in this repo is clear now.

**Comment by mrutkows** [comment]
@daisy-ycguo merged https://github.com/apache/incubator-openwhisk-runtime-docker/pull/27
