### ISSUE TITLE
Track LICENSE and NOTICE issues for `incubator-openwhisk-runtime-java`

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-release#102]
Please use this issue to track any issues surrounding either the [LICENSE.txt](https://github.com/apache/incubator-openwhisk-runtime-java/blob/master/LICENSE.txt) or [NOTICE.txt](https://github.com/apache/incubator-openwhisk-runtime-java/blob/master/NOTICE.txt) file for the associated repository listed in the title.

**Open Issues/PRs**:
- Issue [#3607 - Change the JDK to use openjdk8-openj9 #3607](https://github.com/apache/incubator-openwhisk/issues/3607) (incubator-openwhisk)
- Issue [#137 - JDK license issue for the runtime Java](https://github.com/apache/incubator-openwhisk-release/issues/137)
- Issue [#48 - Change the license for java sdk to Eclipse openj9](https://github.com/apache/incubator-openwhisk-runtime-java/pull/48)

**Closed Issues/Merged PRs**:
- PR [#17 - Add license notice](https://github.com/apache/incubator-openwhisk-runtime-java/pull/17)
- PR [#23 - Add the license headers](https://github.com/apache/incubator-openwhisk-runtime-java/pull/23)
- PR [#29 - Update NOTICE file](https://github.com/apache/incubator-openwhisk-runtime-java/pull/29)
    - Issue [#81 -  Review NOTICE file for incubator-openwhisk-runtime-java](https://github.com/apache/incubator-openwhisk-release/issues/81)
- PR [#32 - Add the licenses of the dependencies into LICENSE file](https://github.com/apache/incubator-openwhisk-runtime-java/pull/32)
- PR [#33 - Add license headers](https://github.com/apache/incubator-openwhisk-runtime-java/pull/33)
    - Issue [#25 - Some source files miss Apache license headers #25](https://github.com/apache/incubator-openwhisk-runtime-java/issues/25)
- PR [#36 - Add scancode using ASF config. to Travis build](https://github.com/apache/incubator-openwhisk-runtime-java/pull/36)
- PR [#38 - Add license header to 1 file](https://github.com/apache/incubator-openwhisk-runtime-java/pull/38)
- PR [#47 - Update .md and .sh files to pass scancode with latest .cfg](https://github.com/apache/incubator-openwhisk-runtime-java/pull/47)
- PR [#49 - Add ASF license headers to all Scala .conf files.](https://github.com/apache/incubator-openwhisk-runtime-java/pull/49)
- PR [#50 - Fix markdown files with a typo. in the Hash license header](https://github.com/apache/incubator-openwhisk-runtime-java/pull/50)
- PR [#51 - Restore the LICENSE and NOTICE to fit the source code release](https://github.com/apache/incubator-openwhisk-runtime-java/pull/51)
- PR [#53 - Fix travis yaml file asf header, change to mini](https://github.com/apache/incubator-openwhisk-runtime-java/pull/53)
- PR [#54 - Last files to need ASF License headers](https://github.com/apache/incubator-openwhisk-runtime-java/pull/54)
- PR [#55 - Fix bad Dockerfile license and use ASF release config](https://github.com/apache/incubator-openwhisk-runtime-java/pull/55)

**Comment by daisy-ycguo** [comment]
A PR https://github.com/apache/incubator-openwhisk-runtime-java/pull/33 is merged. The license header of this repo is clear now.

**Comment by mrutkows** [comment]
@daisy-ycguo merged https://github.com/apache/incubator-openwhisk-runtime-java/pull/33

**Comment by daisy-ycguo** [comment]
A new PR https://github.com/apache/incubator-openwhisk-runtime-java/pull/38 is created to add header to `compileClassCache.sh`

**Comment by mrutkows** [comment]
See discussion here: [Change the JDK to use openjdk8-openj9 #3607](https://github.com/apache/incubator-openwhisk/issues/3607)

regarding a proposal to change the base image we use for Java and the subsequent comments on licenses.
