### ISSUE TITLE
Track LICENSE and NOTICE issues for `incubator-openwhisk-runtime-php`

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-release#103]
Please use this issue to track any issues surrounding either the [LICENSE.txt](https://github.com/apache/incubator-openwhisk-runtime-php/blob/master/LICENSE.txt) or [NOTICE.txt](https://github.com/apache/incubator-openwhisk-runtime-php/blob/master/NOTICE.txt) file for the associated repository listed in the title.

**Open Issues/PRs**:
- _None_

**Closed Issues/Merged PRs**:
- PR [#6 - Add NOTICE file to this repo](https://github.com/apache/incubator-openwhisk-runtime-php/pull/6)
- PR [#7 - Add the license headers to the files missing them](https://github.com/apache/incubator-openwhisk-runtime-php/pull/7)
- PR [#12 - https://github.com/apache/incubator-openwhisk-runtime-php/pull/12](https://github.com/apache/incubator-openwhisk-runtime-php/pull/12)
    - Issue [#83 - Review NOTICE file for incubator-openwhisk-runtime-php](https://github.com/apache/incubator-openwhisk-release/issues/83)
- PR [#13 - Add license header](https://github.com/apache/incubator-openwhisk-runtime-php/pull/13)
    - Issue [#8 - Some source files miss Apache license headers](https://github.com/apache/incubator-openwhisk-runtime-php/issues/8)
- PR [#14 - Add the license of dependencies into LICENSE file](https://github.com/apache/incubator-openwhisk-runtime-php/pull/14)
- PR [#15 - Add scancode using ASF config. to Travis build.](https://github.com/apache/incubator-openwhisk-runtime-php/pull/15)
- PR [#18 - Update .md and .sh files to pass scancode with latest .cfg](https://github.com/apache/incubator-openwhisk-runtime-php/pull/18)
- PR [#19 - Add ASF license headers to all Scala .conf files.](https://github.com/apache/incubator-openwhisk-runtime-php/pull/19)
- PR [#20 - Fix markdown files with a typo. in the Hash license header.](https://github.com/apache/incubator-openwhisk-runtime-php/pull/20)
- PR [#21 - Restore the LICENSE and NOTICE to fit the source code release](https://github.com/apache/incubator-openwhisk-runtime-php/pull/21)
- PR [#22 - Fix travis yaml file asf header, change to mini](https://github.com/apache/incubator-openwhisk-runtime-php/pull/22)
- PR [#23 - Last files to need ASF License headers](https://github.com/apache/incubator-openwhisk-runtime-php/pull/23)
- PR [#24 - Fix bad Dockerfile license and use ASF release config](https://github.com/apache/incubator-openwhisk-deploy-kube/pull/206)

**Comment by daisy-ycguo** [comment]
I suggest to add below files to excluded file list, because they are configuration files with few creativity.

```
  openwhisk-runtime-php/tests/src/test/resources/application.conf
  openwhisk-runtime-php/ansible/environments/local/group_vars/all
  openwhisk-runtime-php/ansible/environments/local/hosts
```

**Comment by mrutkows** [comment]
Vincent merged PR https://github.com/apache/incubator-openwhisk-runtime-php/pull/13#event-1579337468

@daisy-ycguo after this merge, do all files we determined need LICENSE headers have them?  Are there any exclusions that we need to list on markdown here?

**Comment by daisy-ycguo** [comment]
@mrutkows After https://github.com/apache/incubator-openwhisk-runtime-php/pull/13#event-1579337468 is merged, all files have headers except the exclusions in markdown file. The license header of this repo is clear now.

**Comment by mrutkows** [comment]
merged https://github.com/apache/incubator-openwhisk-runtime-php/pull/13#event-1579337468
