### ISSUE TITLE
Check the LICENSE of achieved files in source codes

### ISSUE THREAD

**Issue by daisy-ycguo** [apache/incubator-openwhisk-release#106]
We need to look at these achieved files to check if they has anything bundled because they are in our source codes. 
 
Archives:
 + openwhisk-cli/tests/dat/actions/helloJavaDefaultPackage.jar
 + openwhisk-cli/tests/dat/actions/zippedaction.zip
 + openwhisk-cli/tests/dat/actions/helloJava.jar
 + openwhisk-cli/tests/dat/actions/python3_virtualenv.zip
 + openwhisk-cli/tests/dat/actions/python.zip
 + openwhisk-cli/tests/dat/actions/blackbox.zip
 + openwhisk-cli/tests/dat/actions/python2_virtualenv.zip
 + openwhisk-wskdeploy/tests/src/integration/helloworld/actions/hello.jar
 + openwhisk-wskdeploy/tests/src/integration/docker/actions/exec.zip
 + openwhisk-wskdeploy/tests/src/integration/validate-packages-in-manifest/actions/hello.jar
 + openwhisk-wskdeploy/tests/src/integration/jaraction/src/hello.jar
 + openwhisk-wskdeploy/tests/src/integration/runtimetests/src/helloworld/helloworld.zip
 + openwhisk-wskdeploy/tests/src/integration/runtimetests/src/hello.jar
 + openwhisk/tests/dat/actions/helloSwift311.zip
 + openwhisk/tests/dat/actions/unicode.jar
 + openwhisk/tests/dat/actions/sleep.jar
 + openwhisk/tests/dat/actions/helloJavaDefaultPackage.jar
 + openwhisk/tests/dat/actions/python_virtualenv_name.zip
 + openwhisk/tests/dat/actions/zippedaction.zip
 + openwhisk/tests/dat/actions/helloJava.jar
 + openwhisk/tests/dat/actions/python_virtualenv_dir.zip
 + openwhisk/tests/dat/actions/multiSwift.zip
 + openwhisk/tests/dat/actions/python3_virtualenv.zip
 + openwhisk/tests/dat/actions/python.zip
 + openwhisk/tests/dat/actions/blackbox.zip
 + openwhisk/tests/dat/actions/python2_virtualenv.zip
 + openwhisk-runtime-swift/tests/dat/build/swift311/HelloSwift3.zip
 + openwhisk-runtime-swift/tests/dat/build/swift4.1/SwiftyRequest.zip
 + openwhisk-runtime-swift/tests/dat/build/swift4.1/HelloSwift4Codable.zip
 + openwhisk-runtime-swift/tests/dat/build/swift4.1/HelloSwift4.zip
 + openwhisk-runtime-swift/tests/dat/build/swift4.1/SwiftyRequestCodable.zip
 + openwhisk-runtime-swift/tests/tests/dat/build/swift311/HelloSwift3.zip
 + openwhisk-runtime-swift/tests/tests/dat/build/swift4.1/SwiftyRequest.zip
 + openwhisk-runtime-swift/tests/tests/dat/build/swift4.1/HelloSwift4Codable.zip
 + openwhisk-runtime-swift/tests/tests/dat/build/swift4.1/HelloSwift4.zip
 + openwhisk-runtime-swift/tests/tests/dat/build/swift4.1/SwiftyRequestCodable.zip

**Comment by daisy-ycguo** [comment]
I have checked a few and found "python_virtualenv_name.zip" and "python2_virtualenv.zip" will bring troubles to us.

`openwhisk-cli/tests/dat/actions/python2_virtualenv/virtualenv/lib/python2.7/site-packages/pip/_vendor/packaging/*`
```
# This file is dual licensed under the terms of the Apache License, Version
# 2.0, and the BSD License. See the LICENSE file in the root of this repository
# for complete details.
```

`openwhisk-cli/tests/dat/actions/python2_virtualenv/virtualenv/lib/python2.7/site-packages/pip/_vendor/webencodings/*`
```
"""
    webencodings.labels
    ~~~~~~~~~~~~~~~~~~~
    Map encoding labels to their name.
    :copyright: Copyright 2012 by Simon Sapin
    :license: BSD, see LICENSE for details.
"""
```

`openwhisk-cli/tests/dat/actions/python2_virtualenv/virtualenv/lib/python2.7/site-packages/pip/_vendor/colorama/*`
```
# Copyright Jonathan Hartley 2013. BSD 3-Clause license, see LICENSE file.
```

Python 3 virtual environment has the same issue.

Since these archived python virtual env files are in `tests/dat`, we need to decide if we want to include them in our source code distribution, considering the workload we need to spend on the legal documents.

**Comment by daisy-ycguo** [comment]
I'm not able to unzip below files.
```
openwhisk-runtime-swift/tests/dat/build/swift311/HelloSwift3.zip
openwhisk-runtime-swift/tests/dat/build/swift4.1/SwiftyRequest.zip
openwhisk-runtime-swift/tests/dat/build/swift4.1/HelloSwift4Codable.zip
openwhisk-runtime-swift/tests/dat/build/swift4.1/HelloSwift4.zip
openwhisk-runtime-swift/tests/dat/build/swift4.1/SwiftyRequestCodable.zip
openwhisk-runtime-swift/tests/tests/dat/build/swift311/HelloSwift3.zip
openwhisk-runtime-swift/tests/tests/dat/build/swift4.1/SwiftyRequest.zip
openwhisk-runtime-swift/tests/tests/dat/build/swift4.1/HelloSwift4Codable.zip
openwhisk-runtime-swift/tests/tests/dat/build/swift4.1/HelloSwift4.zip
openwhisk-runtime-swift/tests/tests/dat/build/swift4.1/SwiftyRequestCodable.zip
```
@houshengbo can you try to unzip them and check if they are containing any files under non Apache LICENSE?

**Comment by houshengbo** [comment]
@daisy-ycguo @mrutkows In my opinion, all the license concerns raised in this issue come from the license under the files of test cases. I have submitted a PR to exclude the files of test cases out of the source code artifacts we are about to release. The test cases are used to guard the quality of the source code, and they do not play a part of the features of openwhisk we deliver. They do not contribute to the process to build the binaries and docker images either. The test cases are developer-orientated, not end user-orientated. 

My suggestion is that we can tentatively skip all the licenses going through all the files of test cases for the release process.

In future, if we still want to release the "test" separately, we can come over to tackle the licenses for test cases during the release process. However, this issue can leave us a probable low-priority issue, that whether it is worthy to think of license and avoid the unfriendly licenses, when we write new tests; whether we should rewrite the test cases with apache or apache friendly licenses.

**Comment by mrutkows** [comment]
@daisy-ycguo @houshengbo We should use the issues already created to track by repo. IMO.

**Issues:**
openwhisk (LICENSE): https://github.com/apache/incubator-openwhisk-release/issues/93
openwhisk (NOTICE): https://github.com/apache/incubator-openwhisk-release/issues/75
openwhisk-cli (LICENSE): https://github.com/apache/incubator-openwhisk-release/issues/97
openwhisk-cli (NOTICE): https://github.com/apache/incubator-openwhisk-release/issues/76
...

and so forth.
we should then start examining the specifics for main openwhisk repo., come decisions based upon these test files after discussion in those issues THEN apply the same principles/rules to the other repos. Of course, we should allow for special cases for each repo. therefore, we have separate issues to track these discussions of special cases.

Let us examine first the details of the files for main openwhisk as it should prove to be the most challenging and many more contributors will comment and hopefully help us agree what our community wants to do.
