### ISSUE TITLE
Update LICENSE files to append license information of dependencies

### ISSUE THREAD

**Issue by daisy-ycguo** [apache/incubator-openwhisk-release#109]
According to [Apache policy](http://www.apache.org/legal/release-policy.html#license-file), we shall do this to all component repos in the release: `Append details of the component which are not Apache to the LICENSE file. The component license itself MUST either be appended or else stored elsewhere in the package with a pointer to it from the LICENSE file.`

**Comment by houshengbo** [comment]
@daisy-ycguo Sure. If we decided to remove the files of test cases from the source code release, we do not need to append the licenses coming from the tests.

**Comment by houshengbo** [comment]
Already submitted two PRs:
openwhisk cli: https://github.com/apache/incubator-openwhisk-cli/pull/271
openwhisk: https://github.com/apache/incubator-openwhisk/pull/3550

@daisy-ycguo @mrutkows
