### ISSUE TITLE
Create the project structure to release based on versions

### ISSUE THREAD

**Issue by houshengbo** [apache/incubator-openwhisk-release#11]
We should manage different releases in a more sustainable way. I propose to create a folder names releases under the home directory of this repository. All the historic releases should be available under it. 

**How to trigger the different release?** 
Let's kick off each Travis build for a single release. Since Travis recognizes the build type, so we can trigger the travis build by add a tag. Travis look up folder based on the tag defined, and locate the release to be build.

**What information can be saved for each release?** 
What I can think of is the JSON configuration file, which define the list of projects to be released, and the hash values to be selected.

**How to develop the config.json for each release?** 
We can create one folder named latest under release to keep a config.json as the latest version. Each Travis build triggered by PR will run a build based on this config file. When the release manager finds it ready to release, this file can be copied under the folder for the specific release, and released by adding a tag with the release name.

The repo structure should be like this:
```
releases
 |
 --current
     |
     --config.json
     --LICENSE
     --NOTICE
     --CHANGELOG
 --incubator(Major release number)
     |
     --milestone 1
         |
         --config.json
         --LICENSE
         --NOTICE
         --CHANGELOG
     --milestone 2
         |
         -- config.json
         -- ...
     -- ...
 --1.0.0(Major release number)
     |
     --alpha
         |
         -- config.json
         -- ...
     --beta
         |
         -- config.json
         -- ...
     --final
         |
         -- config.json
         -- ...
     --...
```

**Comment by michaelmarth** [comment]
@chetanmeh how does Apache Sling tie independent module releases into one consistent project release? Also, how are git hashes and semver numbers mapped?

**Comment by houshengbo** [comment]
We can use config.json to define the project set to be released and hash values for each project.
Travis downloads the source code based on the hashes for each project defined inside.

**Comment by jonpspri** [comment]
Why use a directory structure, though?  Most projects I've experienced use VCS tags to identify releases -- the tags are structured as semantic versioning numbers.  Travis, etc, can still source based on the tags, especially if we're packaging/releasing as libraries.  The tags also provide branch points for bug fixes, etc.

**Comment by houshengbo** [comment]
The incubator-openwhisk-release itself is not part of the openwhisk projects to be released. It is a tool to manage the release of all the openwhisk projects. My intention is to make it a one-stop entry to access all the openwhisk projects. It does not have any significance here to use VCS tags for incubator-openwhisk-release. Maybe it is good idea to manage a single project in openwhisk series, like openwhisk, cli, wskdeploy, any runtime project.

I hope the development of incubator-openwhisk-release could be as easy as possible for the users. We fork it under our name, create a PR, and request to merge into master.

Each PR needs to trigger on a Travis build, which only builds based on the files inside release/current, and only needs to verify the code, deploy the code, test the code if necessary. There is no need to package and push the source code upstream to apache directory. We only care about this folder, when we are developing, before any release milestone we decide. As we feel confident in all the hash values saved in release/current/config.json, and decide to propose it as buldled openwhisk projects to release, we can copy them into the folder with name the same to the release name, e.g. 1.0.0 milestone-1. This change can be proposed in a PR as well. 

After we receive the consent from the community to release 1.0.0 milstone-1, we merge the above PR, and tag the commit 1.0.0, so it kick off travis build. Travis sees the tag name, and decide to build based on the config.json under releases/1.0.0/milestone-1(2 or 3)/. In the end, packages of the source code with license, notice, changelog, installation files, etc, will be pushed into the online designated directory of Apache.

**Comment by chetanmeh** [comment]
> how does Apache Sling tie independent module releases into one consistent project release? 

@michaelmarth  In Sling each module is release independently and the resulting maven artifact is deployed in a staging repo which is then voted upon. Depending on project the vote step can be like one of the below ones

1. Sling - Committers then use a [script][1] which downloads the artifact from the staging repo and 
    validates its integrity.
2. In Jackrabbit Oak we use a [different script][2] which does following. Also see [vote mail][3]
    1. Download the staged source zip
    2. Run mvn verify
    3. Perform checksum

There is also a separate starter module which lists all the released and supported modules and produces a single Sling app. This module is currently released annually. 

> Also, how are git hashes and semver numbers mapped?

In Sling and Jackrabbit we rely on maven tooling to create respective tags in git/svn which match the release version. The verify script use the tag to checkout code and build it

[1]: https://github.com/apache/sling-tooling-release/blob/master/check_staged_release.sh
[2]: https://dist.apache.org/repos/dist/dev/jackrabbit/check-release.sh
[3]: https://lists.apache.org/thread.html/073a9bce496813c5fd7b0b83775ca95ab2eed83b971a3bb22b16034f@%3Coak-dev.jackrabbit.apache.org%3E

**Comment by houshengbo** [comment]
@michaelmarth @chetanmeh I am drafting the specifications to implement for this repository, including how release manager uses this repository, where and how to develop a release proposal, how to publish the packages to Apache, etc. We need to develop scripts to download the source code, build the artifacts, and publish them. Furthermore, we plan to run the scripts in Travis CI, which is used to automate the whole process.

> In Sling and Jackrabbit we rely on maven tooling to create respective tags in git/svn which match the release version. The verify script use the tag to checkout code and build it
@chetanmeh Could you give some more detailed information about using maven tooling to create the tags? How does the maven tooling work? Thank you.

**Comment by chetanmeh** [comment]
Maven has a [release plugin][1] which takes care of multiple things like bumping the version number, tag the code and performing test.

For Gradle project we can follow approach taken by [Apache Tapestry][2] which is also a gradle based multi module project and performs all steps required as per Apache project release requirements.

Recently I have added support generating maven pom and artifacts in openwhisk via https://github.com/apache/incubator-openwhisk/pull/3061. So as a next step we can add support for publishing them to staging repo and signing them

[1]: https://maven.apache.org/guides/mini/guide-releasing.html
[2]: https://github.com/apache/tapestry-5/blob/master/build.gradle#L45

**Comment by houshengbo** [comment]
@chetanmeh Thank you. It is very neat to have Maven plugin supported by OpenWhisk core, and any other OpenWhisk project. This release project can directly use the Maven support in each OpenWhisk to generate the artifacts, including source code and complied packages, as long as each openwhisk repo has this Maven support.

**Comment by houshengbo** [comment]
We tentatively closed this issue, because we do not need to implement this complex structure so far.
