### ISSUE TITLE
Set up and document the header rules in OpenWhisk community

### ISSUE THREAD

**Issue by daisy-ycguo** [apache/incubator-openwhisk-release#110]
We shall set up and document the header rules in our community. Here is a draft which we had discussed in the community meeting:

- Documentation (*.md) files (full header)
- Test action files: sort.js, split.js, trigger.swift, niam.py (short header)
- Package action files: catalog package, kafka package (short header)
- Json (*.json) files (ignore)
- YAML (*.yml,*.yaml) files  (full header)
- Dockerfile  (full header)
- Installation script files: all.sh, ansible.sh, misc.sh  (full header)
- Travis files: .travis.yml, build.sh, setup.sh  (full header)
- Makefile  (full header)
- Gradle files: build.gradle, settings.gradle, gradle.properties (ignore)
- IDE config or format config files: .scalafmt.conf, .pyproject, (ignore)
- Template files: docker.j2, nginx.conf.j2, recycle-registry.py.j2 (ignore)

**Comment by daisy-ycguo** [comment]
The decisions rest on:

        * Is it intellectual property? YES (primary factor)
        * Does it impact performance? YES (not as important as protecting Intellectual property)
            * NOTE: these tests MAY be used for perf. testing, but mostly for unit/function testing
        * Will it break Travis builds? MAYBE (we can address this later if needed)

**Comment by mrutkows** [comment]
These license header rules are now documented on this page:
https://github.com/apache/incubator-openwhisk-release/blob/master/docs/license_compliance.md
