### ISSUE TITLE
Document how license and notice files are assembled

### ISSUE THREAD

**Issue by daisy-ycguo** [apache/incubator-openwhisk-release#111]
We shall document how legal files LICENSE.txt and NOTICE.txt are assembled, which can be a reference in future releases.

**Comment by houshengbo** [comment]
The contents of NOTICE and LICENSE have something overlapping. For example, they both explain the licenses of the dependencies.

To me, other packages as in openwhisk cli for instance, like Pflag, unix, sys, etc, are the source code dependencies, not the existing components of the project, so we need to remove them from the notice, and keep them in the LICENSE.

One example for the component of the project can be openwhisk core needs to deploy kafka, zookeeper services, which are not part of the scala source code, but the necessity of the services. They are components of the openwhisk core service. Kafka and Zookeeper are the components not developed by openwhisk, but used by openwhisk to provide services.

It still remains to be resolved that how to differentiate the copyright of dependencies & components and where to put them.

**Comment by houshengbo** [comment]
We have been implementing the policy written here: https://github.com/apache/incubator-openwhisk-release/blob/master/docs/license_assembly.md.
All the existing LICENSE and NOTICE files can be found under https://github.com/apache/incubator-openwhisk-release/tree/master/archive/convenience-binaries.
We can close this issue for now.
