### ISSUE TITLE
Document project position on release of "test" files

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-release#113]
We have decided not to package the test files with the source code artifacts (TAR).  We should document this decision, along with supporting links or examples that show this decision is supported by Apache by policy (and perhaps by example in other projects).

**Comment by houshengbo** [comment]
Apache does not demand us to release the tests or not to release the tests. This can be purely decided by the OpenWhisk community. 

We have already documented the exclusion for the release: https://github.com/apache/incubator-openwhisk-release/blob/master/docs/license_exclusions.md#exclusions-not-part-of-apache-source-code-release, so we can close this issue for now.
