### ISSUE TITLE
Define format of LICENSE file

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-release#120]
Use this issue to propose format, SEPARATORs, how to list/categorize lists of "bundled" vs. "non-bundled" dependencies.

List which LICENSEs (like MIT or LUA) that we decided to copy in OR copy part and provide URL/link. Add these decisions and the template description to the Markdown file:

https://github.com/apache/incubator-openwhisk-release/blob/master/docs/license_compliance.md

We could even check in the sample file here in this repo. for people to copy.

**Comment by daisy-ycguo** [comment]
There are some rules in my mind:
- `whose bits are bundled in source code distribution` means there are third party FILES included in the final released compressed file (for example,  openwhisk-0.3-src.zip).
- `whose bits are bundled in binary distribution` means there are third party FILES included in the final released binary file ( for example, openwhisk-cli-0.3-bin.zip). At this point, I think the packages downloaded during compiling and building should included. 
- I think only `cli` and `wskdeploy` have binary release. For other 10 repositories, we don't have binary release. Most of the dependencies in the other 10 repositories are dependencies during installing and shipped with the docker image. We may need to discuss how to handle this situation.

The format I proposed is:

```
========================================================================
Dependencies whose bits are bundled in source code distribution
========================================================================
No dependencies bundled in the source code distribution

========================================================================
Dependencies whose bits are bundled in binary distribution
========================================================================
This product bundles properties 1.1.1 (https://github.com/magiconair/properties),
which is available under a "2-clause BSD" license. (as below)
```
or if the license file is very long, we can use below format
```
========================================================================
Dependencies whose bits are bundled in binary distribution
========================================================================
This product bundles properties 1.1.1 (https://github.com/magiconair/properties),
which is available under a "2-clause BSD" license. For details, see deps/superwidget/.
```

**Comment by daisy-ycguo** [comment]
I have a question here. How to get the version number of a dependency ?

**Comment by houshengbo** [comment]
@daisy-ycguo @mrutkows We can refer to what are under https://github.com/apache/incubator-openwhisk-release/tree/master/archive/convenience-binaries for the format of the LICENSE and NOTICE.
