### ISSUE TITLE
Document treatment of .conf files as part of LICENSE header exclusions/inclusion

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-release#132]
API Gateway is noted to have multiple ".conf" files. Should these be listed in our project's policy for inclusion or exclusion of ASF license header?

**Comment by daisy-ycguo** [comment]
In my point of view, I think it can be added to the exclusion list because these files are only configuration files, similar as `*.properties` and `*.cfg` which are under exclusion list.

**Comment by houshengbo** [comment]
We have added the headers to all the .conf files in api gateway repo.
