### ISSUE TITLE
Key words like IBM, Adobe, etc should be removed from the source code

### ISSUE THREAD

**Issue by houshengbo** [apache/incubator-openwhisk-release#140]
All the key words, like IBM, Adobe, etc, need to be removed from the source code.

**Comment by csantanapr** [comment]
This is good find Vincent +1

**Comment by daisy-ycguo** [comment]
Are we authorized to remove Adobe copyright from the source code ?

**Comment by mrutkows** [comment]
@daisy-ycguo these keywords are for parts of the code/documentation that do NOT include coopyrights/NOTICE/CREDITS, etc.

**Comment by bdelacretaz** [comment]
https://www.apache.org/legal/src-headers.html#headers has info on how to handle existing copyright notices in donated code.

**Comment by daisy-ycguo** [comment]
Below files are still have `IBM CopyRight` which should be removed.

https://github.com/apache/incubator-openwhisk/tests/src/test/scala/common/Pair.java
https://github.com/apache/incubator-openwhisk-runtime-swift/blob/master/core/swift3.1.1Action/spm-build/Package.swift
https://github.com/apache/incubator-openwhisk-runtime-swift/blob/master/core/swift41Action/spm-build/Package.swift
https://github.com/apache/incubator-openwhisk-runtime-swift/blob/master/core/swift3.1.1Action/spm-build/_WhiskJSONUtils.swift

**Comment by houshengbo** [comment]
We have resolved this issue, since companies have given up their copyright by switching to Copyright 2015-2018 The Apache Software Foundation.
