### ISSUE TITLE
Some license files copied from client-go are not exactly same as original one.

### ISSUE THREAD

**Issue by daisy-ycguo** [apache/incubator-openwhisk-release#141]
Below license files should be copied from openwhisk-client-go, yet [openwhisk-client-go/LICENSE](https://github.com/apache/incubator-openwhisk-client-go/blob/master/LICENSE.txt) doesn't have any words like:
```
Copyright 2015-2016  IBM Corporation
```
https://github.com/apache/incubator-openwhisk-cli/blob/master/licenses/LICENSE-openwhiskclientgo.txt
https://github.com/apache/incubator-openwhisk-wskdeploy/blob/master/licenses/LICENSE-openwhiskclientgo.txt

**Comment by houshengbo** [comment]
We have changed to Copyright 2015-2018 The Apache Software Foundation for all LICENSE and NOTICE files, so this issue can be closed.
