### ISSUE TITLE
Lightbend copyright appears, no LICENSE attribution

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-release#152]
[incubator-openwhisk/blob/master/common/scala/src/main/scala/whisk/core/database/MultipleReadersSingleWriterCache.scala](https://github.com/apache/incubator-openwhisk/blob/master/common/scala/src/main/scala/whisk/core/database/MultipleReadersSingleWriterCache.scala) contains:

```
/*
 * Cache base implementation:
 * Copyright (C) 2017 Lightbend Inc. <http://www.lightbend.com/>
 */
```

Where did this code come from (project?). Under what license?  why is it not attributed?

Assume they came from this GitHub project:
https://github.com/lightbend/config

which has an Apache  2 license (as a project)
https://github.com/lightbend/config/blob/master/LICENSE-2.0.txt

but, if we copied their code (from a file) we need to find that file to assure Apache2

**Comment by markusthoemmes** [comment]
This is from the spray project. We can probably revisit/remove this code as it is available in akka-http now as well.

**Comment by houshengbo** [comment]
@markusthoemmes Could you change the implementation of this file? Change it or remove it.
If not, we need to add the license and notice for this file.
