### ISSUE TITLE
Change JDK used to build main OW to be "pluggable" for building Source (release)

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-release#153]
Related to Issue [#3607 - Change the JDK to use openjdk8-openj9](https://github.com/apache/incubator-openwhisk/issues/3607).

We need to show that we allow people to build with a JDK of their choosing (we can default to one like Oracle), but should likely make this pluggable via an Env. var. (or configurable parm.)

**Comment by houshengbo** [comment]
@mrutkows We have already resolved this issue, since both openwhisk and openwhisk runtime java have adopted Open JDK from adoptopenjdk.
