### ISSUE TITLE
Swift runtime has "SPM" builds (binaries) using ext. code with no license attribution

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-release#156]
Both Swift 3.1 and Swift 4 runtimes produce "spm-build" directories indicative of use of 3rd party tools but we have no license attribution.

See: https://github.com/spmjs/spm-build

**Comment by csantanapr** [comment]
spm-build not related at all to spmjs

spm stands for swift package manager 
spm-build is just a directory name we picked as the location where the code will get compiled
