### ISSUE TITLE
Verify source code release TARs do not contain "ignore" and project tooling files.

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-release#159]
including, but not limited to:
```
.gitignore
.dockerignore
.git
.github
.pydevproject
```

**Comment by mrutkows** [comment]
@houshengbo if you have confirmed this by inspection of a TAR you generated for the apigateway repo. then feel free to close this issue.  I would appreciate a link to the PR (and file) where you fixed (and configured) this.

**Comment by houshengbo** [comment]
duplicate of the issue https://github.com/apache/incubator-openwhisk-release/issues/161
