### ISSUE TITLE
Exclude "tests" directories in source code release archives from all repos.

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-release#163]
It appears that we have many JAR and ZIP files where we do not have the source or the source is not compiled as part of the build process.  Discussing this with Carlos when bringing this up on the Apache OW Tech. interchange call it seemed the general consensus was to (for now) remove the "tests" directory structure when publishing the source TAR files.

This would likely need to happen also for all of the repos. that will be part of our release including:
```
incubator-openwhisk-apigateway/tests
incubator-openwhisk-catalog/tests
incubator-openwhisk-cli/tests
incubator-openwhisk-runtime-docker/tests
incubator-openwhisk-runtime-java/tests
incubator-openwhisk-runtime-nodejs/tests
incubator-openwhisk-runtime-php/tests
incubator-openwhisk-runtime-python/tests
incubator-openwhisk-runtime-swift/tests
incubator-openwhisk-runtime-swift/tests/tests
incubator-openwhisk-utilities/scancode/tests
incubator-openwhisk-wskdeploy/tests
incubator-openwhisk/tests
```

**Comment by mrutkows** [comment]
@houshengbo Can we confirm that all TAR files we produce for source release have their "tests" folders/directory trees deleted from final packaging?

**Comment by houshengbo** [comment]
This issue is fixed by : https://github.com/apache/incubator-openwhisk-release/pull/172
