### ISSUE TITLE
Assure `lua_modules` directory tree (test deps.) is not part of source or binary release.

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-release#166]
API Gateway installs several Lua modules (via luarocks package installer) that are copied as part of the Travis build scipts (see https://github.com/apache/incubator-openwhisk-apigateway/blob/master/tests/install-deps.sh).

including:
```
# Install test dependencies
mkdir -p lua_modules
luarocks install --tree=lua_modules lua-cjson
luarocks install --tree=lua_modules luabitop
luarocks install --tree=lua_modules luasocket
luarocks install --tree=lua_modules sha1
luarocks install --tree=lua_modules md5
luarocks install --tree=lua_modules net-url
luarocks install --tree=lua_modules luafilesystem
```

None should be part of any Apache release archive/package.

**Comment by houshengbo** [comment]
@mrutkows Tests folder is excluded, since there will not be any lua_modules module to be released.
