### ISSUE TITLE
API Gateway needs to build using OpenJDK instead of Oracle JDK8

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-release#167]
Travis pulls in Oracle JDK8 ...

```API Gateway builds using Oracle JDK8 (java-8-oracle), JAVA_HOME will be set to /usr/lib/jvm/java-8-oracle```

**Comment by houshengbo** [comment]
@mrutkows I did not find the line downloading the JDK, could you list the source code file here?

**Comment by csantanapr** [comment]
Apigateway doesn’t need a jdk

**Comment by csantanapr** [comment]
Java is used in gradle tests in Travis but apigateway doesn’t use java

**Comment by mrutkows** [comment]
saw the above messaage in a failed travis build log (pasted message), it may be that they have tests from other repos. that are being copied in and built (like main openwhisk repo.).  Then that is not a source code problem, but might be a binary release problem in the future.
the message in the issue was copied/pasted from a Travis log for apigateway… i should have copied the larger context, sorry  I agree, this is likely part of the testing and just wanted to record this as something to investigate to make sure we found no deps. on JDK.
