### ISSUE TITLE
Allow user to change to use their chose JDK and document (multiple repos)

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-release#169]
We should provide a means for user to change the build to use a JDK of their choice; tat is, we need a means to configure the JDK location (dynamically or statically) and create user documentation telling them how to. These instructions and process should be the same for all repos. that use a JDK (e.g., main openwhisk, apigateway and runtime java).

This problem surfaced and is related to issue: https://github.com/apache/incubator-openwhisk-release/issues/167

**Comment by mrutkows** [comment]
Note: related to issue https://github.com/apache/incubator-openwhisk-release/issues/153

**Comment by houshengbo** [comment]
@markusthoemmes @rabbah Do you know what could be the reason?

**Comment by csantanapr** [comment]
@houshengbo can you post a PR to see how you switched to openjdk?
