### ISSUE TITLE
Step 2: Verify the compliance of the source code

### ISSUE THREAD

**Issue by houshengbo** [apache/incubator-openwhisk-release#17]
Each source code file needs to have Apache licensing header at the top. We need to implement a script called "verify_source_code.sh", to check the valid headers, after Step 1: download the source code.

We should use the directory where all the source code is saved, and the list of project names parsed in Step 1, as the input to this script.

Sub-issues can be opened to track this epic.

**Comment by houshengbo** [comment]
issue 5

I have created a gradle support to package the source code of wskdeploy, which is merged already: https://github.com/apache/incubator-openwhisk-wskdeploy

Please try to see if you can develop a bash script, to verify all the sources in a tar.gz file contain the apache headers.

**Comment by daisy-ycguo** [comment]
@houshengbo I failed to run `./gradlew taredSources`. I got a NPE.

But I run RAT with a folder option.
`java -jar apache-rat-0.9-SNAPSHOT.jar wskdeploy_folder_name > rat_report.txt`

And it creates a report.

**Comment by houshengbo** [comment]
@daisy-ycguo Please check this page: https://plugins.gradle.org/plugin/org.nosphere.apache.rat/0.3.1.

There is a gradle RAT plugin. After we import the RAT plugin in build.gradle, we can generate the report by running ./gradlew rat.

**Comment by daisy-ycguo** [comment]
@houshengbo I know you implemented a gradle target `taredSources`  to package source files into a compressed file. It is a easy way to audit headers if we have a gradle target `rat` to check headers. I think that's the reason you prefer to use the gradle way. I have a PR to wskdeploy. You can checkout and have a try.

Is it easy to include a Gradle command in a travis job which will check headers for a PR? I see most travis jobs are using shell script directly. If we call a gradle command, we must install gradle before we can use it. Do you know how to install gradle in a travis job image ? Can you find a reference ?

**Comment by houshengbo** [comment]
@daisy-ycguo In fact, if we have the gradle package available under each repository, we can run the gradle command under each repo.

The gradle package is like: https://github.com/apache/incubator-openwhisk-wskdeploy/tree/master/gradle

**Comment by houshengbo** [comment]
We have already created a script: https://github.com/apache/incubator-openwhisk-release/blob/master/tools/verify_source_code.sh, to generate the report of the license headers and the existence of notice and license files for each repo.
