### ISSUE TITLE
Change directory from 'license' to 'licenses' for runtime-swift

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-release#170]
The runtime-swift binary-release archive of project licenses is under directory  named 'license' (singular), but the convention is to use the directory name 'licenses' (plural).  Here is the directory that contains the folder that should be renamed to be plural:
https://github.com/apache/incubator-openwhisk-release/tree/master/archive/convenience-binaries/openwhisk-runtime-swift

This was originally reported in this issue https://github.com/apache/incubator-openwhisk-runtime-swift/issues/52
in the runtime-swift repo. which I will close.

**Comment by houshengbo** [comment]
@mrutkows This issue is fixed.
