### ISSUE TITLE
Automate checks to verify 'tests' (and other files) are removed from source release TAR files

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-release#171]
We need some utility that can programmatically confirm that specific folder/files are removed from the final TAR/ZIP files we release (as part of source release primarily).

For example, we exclude all ```tests``` directories (and all their contents) from all repos. final source code release TAR files we upload to Apache SVN; however, we have no separate tool to verify the build step correctly removed files/folders we have identified.

Other examples includes a "test" folder from apigateway repo. that is not named "tests":
```
lua_modules
```
and "ignore" files (from tooling) such as:
```
.bin
.dockerignore
.git
.gitattributes
.github
.gitignore
.jshintrc
.profiling.*
.pydevproject
.rat-excludes
```

**Comment by mrutkows** [comment]
@houshengbo if you have confirmed this by inspection of a TAR you generated for the apigateway repo. then feel free to close this issue.

**Comment by houshengbo** [comment]
@mrutkows I confirm this issue is resolved.
