### ISSUE TITLE
Can we remove gradle-wrapper.jar from TAR files?

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-release#177]
We identified this as the only/last remaining .jar files in our source release, but it was indicated to me that we could not build without them.  However, this seems to need to be revisited and understand the alternatives (e.g., have user build gradle jar themselves)?

Is there a precedent one way or other? Also, what can we do documentation-wise as well?

**Comment by houshengbo** [comment]
@mrutkows As we discussed, we can keep the gradle wrapper in the source code release. Apache Beam can be our reference for the wrapper solution.
