### ISSUE TITLE
Add DISCLAIMER files to each openwhisk repo

### ISSUE THREAD

**Issue by houshengbo** [apache/incubator-openwhisk-release#180]
At the stage of being incubated, OpenWhisk projects need to include DISCLAIMER in order to indicate that the project is under incubation in Apache.

PRs to resolve this issue:
OpenWhisk Catalog: https://github.com/apache/incubator-openwhisk-catalog/pull/280
OpenWhisk API Gateway: https://github.com/apache/incubator-openwhisk-apigateway/pull/308
OpenWhisk CLI: https://github.com/apache/incubator-openwhisk-cli/pull/312
OpenWhisk Client Go: https://github.com/apache/incubator-openwhisk-client-go/pull/93
OpenWhisk wskdeploy: https://github.com/apache/incubator-openwhisk-wskdeploy/pull/952
OpenWhisk: https://github.com/apache/incubator-openwhisk/pull/3727
OpenWhisk Runtime Java: https://github.com/apache/incubator-openwhisk-runtime-java/pull/57
OpenWhisk Runtime Nodejs: https://github.com/apache/incubator-openwhisk-runtime-nodejs/pull/56
OpenWhisk Runtime Swift: https://github.com/apache/incubator-openwhisk-runtime-swift/pull/65
OpenWhisk Runtime Python: https://github.com/apache/incubator-openwhisk-runtime-python/pull/28
OpenWhisk Runtime PHP: https://github.com/apache/incubator-openwhisk-runtime-php/pull/26
OpenWhisk Runtime Docker: https://github.com/apache/incubator-openwhisk-runtime-docker/pull/44

**Comment by mrutkows** [comment]
@houshengbo are you continuing to add them to the other release repos.? that is:
incubator-openwhisk
incubator-openwhisk-runtime-x (nodejs, java, python, php, swift)

**Comment by houshengbo** [comment]
@mrutkows yes I am doing it.
