### ISSUE TITLE
Step 6: Package the artifacts

### ISSUE THREAD

**Issue by houshengbo** [apache/incubator-openwhisk-release#20]
This is a major step.

By specifying the release name, and the hash values or tags, we need to build and generate the artifacts for the release. If no hash value or tags is defined for each openwhisk repo, we can pick up the current commit. We can use the json configuration file to save the hash values, if Step 1 did not apply it.

Each OpenWhisk project needs to have one compiled package, and one source code package. This is probably where the Maven release plugin can play out. As we have already downloaded the source code of each OpenWhisk repository, Maven command can be used to generate all the artifacts. 

One challenge we can think of is that OpenWhisk consists of projects based on different programming languages individually, we need to figure out how to package the artifacts differently for different languages, by using the similar or consistent build environment. OpenWhisk core is based on Scala, CLI is based on Go, wskdeploy is based on Go, api gateway
is based on lua, runtime project may be based on its native runtime language, etc. 

Artifacts should be signed in this step with PGP tool.

In general, this step calls for more investigation and man power to work on.

Sub-issues can be opened to track this epic.

**Comment by michaelmarth** [comment]
@houshengbo one question: I noticed that you do not mention publishing Docker containers as artifacts. I think that the language-specific artifacts are more important indeed, so I would not want to change that. However, I wonder if containers are an additional artifact you have in mind - maybe down the line?

**Comment by houshengbo** [comment]
@michaelmarth The docker images are under my radar. I will add them into the spec.

**Comment by houshengbo** [comment]
@daisy-ycguo Daisy, could you look at how tools, like Maven, can build and publish the artifacts for us. We should be able to configure the staging repo with Maven as well.

I have already created the folder for openwhis to stage: https://dist.apache.org/repos/dist/dev/incubator/openwhisk/
and to release: https://dist.apache.org/repos/dist/release/incubator/openwhisk/.

**Comment by houshengbo** [comment]
Let's start from packaging source code.

All the openwhisk repos to be released need to have a gradlew task named "taredSources" to package the source code under build folder, and cleanBuild to remove all the files under build folder in each repo.
