### ISSUE TITLE
tutorial should define OPENWHISK_HOME first before using it in a command

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk-release#212]
from https://dist.apache.org/repos/dist/dev/incubator/openwhisk/apache-openwhisk-0.9.0-incubating-rc1/doc/INSTALL.md

to avoid conflicting values for the env var, the instructions should first tell you to define OPENWHISK_HOME before running this command.

and maybe we should avoid that anyway - you're already assuming in the build steps that you're in the incubator-openwhisk directory, users will need to cd ansible... so why not reset the path and avoid introducing this var.

```
## Run OpenWhisk

The easiest way to try out OpenWhisk is to use OpenWhisk CLI. Please find the configuration [here](https://github.com/apache/incubator-openwhisk/blob/master/docs/cli.md).
For example, you can configure you CLI with the following command, if you have deployed OpenWhisk locally:

```
$ wsk property set --apihost 172.17.0.1 --auth $(cat ${OPENWHISK_HOME}/ansible/files/auth.guest)
```

The environment variable $OPENWHISK_HOME points to the directory incubator-openwhisk.
```

**Comment by houshengbo** [comment]
Will update the doc for this issue together with #213
