### ISSUE TITLE
adapt rcverify to check for executables without relying on file name filters

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk-release#262]
`rcverify` scans a RC for executables by checking files for `+x`. This can lead to false positives and negatives (the former because there are exemptions for `.sh` files for example that are expected to be shell scripts).

arguably, it is better for the verifier to check that the file type is not binary.

cc @dgrove-oss

**Comment by dgrove-oss** [comment]
Fixed in #270
