### ISSUE TITLE
Use Apache Tentacles to create a LICENSE and NOTICE report

### ISSUE THREAD

**Issue by daisy-ycguo** [apache/incubator-openwhisk-release#3]
Apache Tentacles™ is a part of Apache Creadur, which helps audit in bulk components uploaded to a staging repository. 

This proposal is to enable Apache Tentacles after OpenWhisk released archives uploaded to a staging repo, e.g. [repository.apache.org](https://repository.apache.org/content/repositories). The tool will download all the archives, unpack them and create a report of what is there, including all LICENSE and NOTICES files. 

It can help the audit easily.

Steps to install and use this tool:
1. `git clone https://github.com/apache/creadur-tentacles.git`
2. `cd creadur-tentacles` & `mvn clean install`
3. `java -ea -jar apache-tentacles-0.1-SNAPSHOT-jar-with-dependencies.jar https://repository.apache.org/content/repositories/<openwhisk-release-folder>/`

It will create a folder named as `<openwhisk-release-folder>` containing a report in HTML files. The folder looks like:
-<openwhisk-release-folder>
|-achives.html
|-licenses.html
|-notices.html
|-......<several licenses.html and notices.html for every zip/jar file>
|-content
|-repo

**Comment by csantanapr** [comment]
@daisy-ycguo No description provided

**Comment by csantanapr** [comment]
I google "Apache Tentacles"
Are you referring to this? http://creadur.apache.org/tentacles/
In what step of cutting a release will this be use?

**Comment by mrutkows** [comment]
@csantanapr I think this is a placeholder... Vincent is going to outline process proposal and Daisy will add to that list.  This should be done on the ZIP/TAR of each repo (source initially) to assure Apache required metadata files are present.

**Comment by daisy-ycguo** [comment]
@csantanapr Description updated.

**Comment by daisy-ycguo** [comment]
I think we may need a script to automate the audit of LICENSE and NOTICE after the report is generated.

**Comment by houshengbo** [comment]
This is an interesting tool. I guess this part can be added to the phase release of source code, as I proposed in https://github.com/apache/incubator-openwhisk-release/pull/15.

**Comment by houshengbo** [comment]
@daisy-ycguo Can we run this tools locally before we upload anything to the staging repository?
For example, locally on the machine or in travis build, we download all the source code. Before we zip them, can we use this tool to generate the NOTICE and license, based on my local directory of source code?

**Comment by daisy-ycguo** [comment]
@houshengbo The tool can be executed locally but the staging repo must be online and cannot be a local repo. This tool is not used to generate NOTICE and LICENSE but used to `check` NOTICE and LICENSE. Those files must be added manually to every different source package.

**Comment by houshengbo** [comment]
LoL. This is what we can do: we add the NOTICE and LICENSE, package them into jars, or whatever zips, launch them into staging. Use this tool to verify the NOTICE and LICENSE later.

What if we run the staging repo service ocally, so that we can access via localhost. Still unable to use this tool?

**Comment by houshengbo** [comment]
@daisy-ycguo I have tried the Tentacles to generate the report for our staging directory, I found all the license and notice report empty, even if I put LICENSE, LICENSES, LICENSE.txt and LICENSES.txt inside the tar.gz.

**Comment by houshengbo** [comment]
We decided to create the license and notice files manually so far for each openwhisk repo, since Apache Tentacles did not meet our need in terms of file creation.
