### ISSUE TITLE
Step 9: Create comprehensive step-wise process checklist on README

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-release#32]
Please see: https://spark.apache.org/release-process.html

for what we should be aiming for once all other steps are well understood (and documented individually).  They eventually all need to be brought together in some manner to create a top-to-bottom step-wise checklist.

**Comment by houshengbo** [comment]
@mrutkows 
I think the tutorial can play the same role so far: https://github.com/apache/incubator-openwhisk-release#instruction-to-use-openwhisk-release
