### ISSUE TITLE
Can we anonymize the PGP key configuration?

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-release#41]
Is there a way that we can anonymize (or use a dedicated key not from an individual at IBM)? 

tools/pgp_key_gen.conf
```
Showing the top two matches Last indexed 6 days ago
Name-Real: Vincent Hou
Name-Comment: Release manager of OpenWhisk
Name-Email: shou@us.ibm.com
Expire-Date: 0
Passphrase: openwhisk
%commit
%echo done
```

tools/travis/import_pgp_key.sh
```
Showing the top two matches Last indexed 12 hours ago
gpg --allow-secret-key-import --import $PARENTDIR/key_sec.gpg

expect -c "spawn gpg --edit-key hou@us.ibm.com trust quit; send \"5\ry\r\"; expect eof"
```

**Comment by houshengbo** [comment]
@mrutkows I am wondering if we have a dedicated account, which is able to access apache svn. I would like to remove my credentials as well.
@csantanapr Do we have one?

**Comment by csantanapr** [comment]
I gave the following feedback:
Do the testing of the release in Travis. (deploy openwhis, run some tests)
Do the zip/tar, md5 and sign on Apache Jenkins.

Apache Jenkins nodes are already configure with svn
Here is an example of a Job https://builds.apache.org/view/Incubator%20Projects/job/incubator-netbeans-html4j-release

I suggest to create a jenkins job, where release manager for the week can enter some form fields if necessary and start jenkins job, this will kick Travis to run testing, then when done, continue with tar/zip, sign, md5, and copy to svn. 
Or have release manager tag the repo, and this kicks Travis, and then Travis kicks jenkins to do zip/tar, sign, md5, and copy to svn

The PGP key can be generated with apache id of one of the PPMC member (user@apache.id) like 
Like netbean project
```
Signed with my jtulach@apache.org key approved for NetBeans project with command:
$ gpg -u f4c8f51d -ab incubating-netbeans-html4j-1.5.1.zip
$ cat incubating-netbeans-html4j-1.5.1.zip.asc 
```
![image](https://user-images.githubusercontent.com/1094878/36517532-718741d8-1750-11e8-8b58-9f67c56dfa70.png)

**Comment by houshengbo** [comment]
@csantanapr I think it is more straight forward that we can manage all the steps here in Travis. Otherwise, it is complicated to trigger another Jenkins job in Travis job. It will be more difficult to maintain. 

Currently, I encrypt personal credentials to sign and update the SVN. As long as we have a general SVN account(usernane and password), I can encrypt it in travis. For PGP signature, I can change it to an apache id.

**Comment by houshengbo** [comment]
For SVN, I currently encrypted my username and password in Travis to access the SVN.
For PGP signature, I can change the name and email address to any name and address, even virtual ones, because they have just been used as an identity marker to indicate who signed the artifacts.

**Comment by csantanapr** [comment]
Yeah encrypting the all the bits in Travis also works for me
