### ISSUE TITLE
Add the support to verify the apache licensing header for all the source code

### ISSUE THREAD

**Issue by houshengbo** [apache/incubator-openwhisk-release#5]
We need to make sure each source code file has a valid and complete Apache licensing header.
We can use the existing scanCode available in openwhisk-utilities, which is absolutely one option for us.
Another option worth being investigated is the RAT in Apache.

**Comment by daisy-ycguo** [comment]
Apache Rat is a release audit tool, focused on licenses.

Steps of installation and usage:
1. git clone https://github.com/apache/rat.git
2. mvn clean install
3. java -jar apache-rat-0.9-SNAPSHOT.jar -a <folder>

The command will generate a report like:
```
*****************************************************
Summary
-------
Generated at: 2018-01-25T11:05:30+08:00
Notes: 0
Binaries: 0
Archives: 0
Standards: 2

Apache Licensed: 0
Generated Documents: 0

JavaDocs are generated and so license header is optional
Generated files do not required license headers

2 Unknown Licenses

*******************************

Unapproved licenses:

  ./test/b.py
  ./test/c.txt

*******************************

Archives:

*****************************************************
  Files with Apache License headers will be marked AL
  Binary files (which do not require AL headers) will be marked B
  Compressed archives will be marked A
  Notices, licenses etc will be marked N
 !????? ./test/b.py
 !????? ./test/c.txt

*****************************************************
 Printing headers for files without AL header...


=======================================================================
==./test/b.py
=======================================================================
bb

=======================================================================
==./test/c.txt
=======================================================================
aa
```

And it will generate a new file `b.py.new` with the Apache License 2.0 header. If we want to update the file directly, we can use `--force`option.

**Comment by houshengbo** [comment]
@daisy-ycguo I think this tool works functionally similar to what is in our utilities.
@mrutkows It looks like we can use this tool in our release process. We have two options to verify the headers.   BTW, if we are in favor of apache tools, do we like to add RAT into openwhisk utilities? (low priority)

**Comment by houshengbo** [comment]
We have already created a script: https://github.com/apache/incubator-openwhisk-release/blob/master/tools/verify_source_code.sh, to generate the report of the license headers and the existence of notice and license files for each repo.
