### ISSUE TITLE
Verify API Gateway legal NOTICE / CREDITS files ack. licenses/contribs.

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-release#63]
In our Apache proposal I noted the following:
```
Adobe-API-Platform

    Openresty - Licensed under the 2-clause BSD license - https://github.com/openresty/ngx_openresty#copyright--license NGINX License - http://nginx.org/LICENSE Luajit - MIT License - http://luajit.org/luajit.html PCRE - BSD license - http://www.pcre.org/licence.txt NAXSI: GPL - is not compiled with the Gateway API code. Instead The API Gateway project contains instructions for developers on where to get NAXSI code (under GPL) ZeroMQ / ØMQ - Linked Dynamically in separate module libzmq - LGPL license with SPECIAL EXCEPTION GRANTED BY COPYRIGHT HOLDERS - https://github.com/zeromq/libzmq czmq - High Level C binding for libzmq - MPL v2 license https://github.com/zeromq/czmq
```

we need to assure the API repo. properly records these licenses (NOTICE file) and attributions

**Comment by houshengbo** [comment]
closes: https://github.com/apache/incubator-openwhisk-release/issues/9

**Comment by houshengbo** [comment]
@mrutkows I had a PR in the openwhisk-apigateway repo to replace and add the license headers: https://github.com/apache/incubator-openwhisk-apigateway/commit/6165ffe5395a5827f46c52d767ba89862fb91e3b
I am not sure if that can resolve your concerns.

**Comment by daisy-ycguo** [comment]
link to #108

**Comment by houshengbo** [comment]
@mrutkows This issue has been resolved, since Adobe contributors have changed the headers.
