### ISSUE TITLE
Review all (12) NOTICE files for contents

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-release#87]
Track the review of notice files in these individual issues:

openwhisk: https://github.com/apache/incubator-openwhisk-release/issues/75
cli: https://github.com/apache/incubator-openwhisk-release/issues/76
client-go: https://github.com/apache/incubator-openwhisk-release/issues/77
apigateway: https://github.com/apache/incubator-openwhisk-release/issues/78
catalog: https://github.com/apache/incubator-openwhisk-release/issues/79
runtime-docker: https://github.com/apache/incubator-openwhisk-release/issues/80
java: https://github.com/apache/incubator-openwhisk-release/issues/81
nodejs: https://github.com/apache/incubator-openwhisk-release/issues/82
php: https://github.com/apache/incubator-openwhisk-release/issues/83
python: https://github.com/apache/incubator-openwhisk-release/issues/84
swift: https://github.com/apache/incubator-openwhisk-release/issues/85
wskdeploy: https://github.com/apache/incubator-openwhisk-release/issues/86

**Comment by houshengbo** [comment]
@mrutkows We are fine with the LICENSE and NOTICE files so far, since we expect source code release only as the first time release.
