### ISSUE TITLE
Track LICENSE and NOTICE issues for `incubator-openwhisk-wskdeploy`

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-release#94]
Please use this issue to track any issues surrounding either the [LICENSE.txt](https://github.com/apache/incubator-openwhisk-wskdeploy/blob/master/LICENSE.txt) or [NOTICE.txt](https://github.com/apache/incubator-openwhisk-wskdeploy/blob/master/NOTICE.txt) file for the associated repository listed in the title.

**Open Issues/PRs**:
- Issue [#175 - Remove wskdeploy specification PDFs (archives) and diagram from source release](https://github.com/apache/incubator-openwhisk-release/issues/175)

**Closed Issues/Merged PRs**:
- PR [#709 - Add Apache License](https://github.com/apache/incubator-openwhisk-wskdeploy/pull/709)
    - Issue [#716 - Some source files are missing Apache license headers](https://github.com/apache/incubator-openwhisk-wskdeploy/issues/716)
- PR [#842 - Update NOTICE file](https://github.com/apache/incubator-openwhisk-wskdeploy/pull/842)
    - Issue [#86 - Review NOTICE file for incubator-openwhisk-wskdeploy](https://github.com/apache/incubator-openwhisk-release/issues/86)
- PR [#844 - Add the LICENSE and NOTICE into the binary packages](https://github.com/apache/incubator-openwhisk-wskdeploy/pull/844#pullrequestreview-110627777)
- PR [#882 - Add ASF license headers to API Gateway integration test's javascript source files #882](https://github.com/apache/incubator-openwhisk-wskdeploy/pull/882)
- PR [#883 - Add license header to 3 files #883](https://github.com/apache/incubator-openwhisk-wskdeploy/pull/883)
- PR [#888 - Change the LICENSE file into the format defined in release #888](https://github.com/apache/incubator-openwhisk-wskdeploy/pull/888#event-1606423092)
- PR [#896 - Remove Apache long header if short header exists](https://github.com/apache/incubator-openwhisk-wskdeploy/pull/896)
    - Issue [#133 - Why do wskdeploy "example' .js files have both FULL and MINI ASF headers?](https://github.com/apache/incubator-openwhisk-release/issues/133) - Daisy volunteered to look at (issue in release repo.)
- PR [#897 - Fix all files with Hash license header to fix typo](https://github.com/apache/incubator-openwhisk-wskdeploy/pull/897)
- PR [#902 - Restore the LICENSE and NOTICE to fit the source code release](https://github.com/apache/incubator-openwhisk-wskdeploy/pull/902)
- PR [#907 - Fix makefile ASF header & use ICF as example of curl usage.](https://github.com/apache/incubator-openwhisk-wskdeploy/pull/907)
    - Note: Revert failed on PR #911, fixed in PRs #914 and #915
- PR [#912 - Fix travis yaml file asf header, change to mini](https://github.com/apache/incubator-openwhisk-wskdeploy/pull/912)
- PR [#914 - Fix mini license header](https://github.com/apache/incubator-openwhisk-wskdeploy/pull/914)
    - Issue [#889 - Change all manifest.yaml and deployment.yaml files to use Mini ASF license header](https://github.com/apache/incubator-openwhisk-wskdeploy/issues/889)
    - Issue [#909 - Fix LICENSE headers in all YAML/.js under "tests" folder](https://github.com/apache/incubator-openwhisk-wskdeploy/issues/909)
- PR [#915 - Fix last few files missing correct ASF header and EOF errors](https://github.com/apache/incubator-openwhisk-wskdeploy/pull/915)
- PR [#921 - Add ASF license header to .gradle files.](https://github.com/apache/incubator-openwhisk-wskdeploy/pull/915)
- PR[#952 - Add the DISCLAIMER file for Apache incubator project](https://github.com/apache/incubator-openwhisk-wskdeploy/pull/952#pullrequestreview-126509345)

**PRs Closed/Reverted/Revisit**:
- PR [#886 - adding license files](https://github.com/apache/incubator-openwhisk-wskdeploy/pull/886#pullrequestreview-117017732)
- PR [#887 - an attempt to cleanup list of deps](https://github.com/apache/incubator-openwhisk-wskdeploy/pull/887)
   - Closed - Priti determined the dependency cross-ref. was too tangled to unknot quickly.  Should this be revisited in future (i.e., open a future issue?)?

**Comment by mrutkows** [comment]
@daisy-ycguo @houshengbo Addressing the discussion in PR https://github.com/apache/incubator-openwhisk-wskdeploy/pull/844#pullrequestreview-110627777, we have need to document that we have decided not to include the generated "i18n_resources.go" file and are unable to add a header comment to its source input file (i.e., en_US.all.json or other similar language/country coded JSON files).  

IMO, we should include this decision/logic in this repo's LICENSE file.

**Comment by daisy-ycguo** [comment]
Issue was created https://github.com/apache/incubator-openwhisk-wskdeploy/issues/716, and also a PR was merged https://github.com/apache/incubator-openwhisk-wskdeploy/pull/709. 

Yet there is still a TODO: change the test files to short license header.

**Comment by mrutkows** [comment]
PR https://github.com/apache/incubator-openwhisk-wskdeploy/pull/709 was merged.  Are there any more files missing ASF headers?

**Comment by mrutkows** [comment]
Please note these files now have both Full and Mini. ASF headers.  Opened issue: https://github.com/apache/incubator-openwhisk-release/issues/133

**Comment by mrutkows** [comment]
PR https://github.com/apache/incubator-openwhisk-wskdeploy/pull/882/files was merged; this should be the last of the files with no ASF license headers for this repo.

**Comment by daisy-ycguo** [comment]
I submitted a PR to add headers to the left 3 files https://github.com/apache/incubator-openwhisk-wskdeploy/pull/883. This should be the last PR, I think. After it gets merged, there should be no files missing header in wskdeploy repo.

**Comment by houshengbo** [comment]
We can close this issue, since all the PRs have been merged. 
The issue https://github.com/apache/incubator-openwhisk-release/issues/175 is being fixed by another PR.
