### ISSUE TITLE
Track LICENSE and NOTICE issues for `incubator-openwhisk-catalog`

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-release#96]
Please use this issue to track any issues surrounding either the [LICENSE.txt](https://github.com/apache/incubator-openwhisk-catalog/blob/master/LICENSE.txt) or [NOTICE.txt](https://github.com/apache/incubator-openwhisk-catalog/blob/master/NOTICE.txt) file for the associated repository listed in the title.

**Open Issues/PRs**:
- _None_

**Closed Issues/Merged PRs**:
- PR [#257 - Add the support to package source code](https://github.com/apache/incubator-openwhisk-catalog/pull/257/files) - old/no longer valid
- PR [#260 - Add the LICENSE and NOTICE files](https://github.com/apache/incubator-openwhisk-catalog/pull/260)
- PR [#262 - Add the license headers](https://github.com/apache/incubator-openwhisk-catalog/pull/262)
    - Issue [#256 - A list of source files missing Apache license headers](https://github.com/apache/incubator-openwhisk-catalog/issues/256)
- PR [#265 - Use the strict ASF release specific configuration for scancode.py](https://github.com/apache/incubator-openwhisk-catalog/pull/265)
- PR [#266 - Update NOTICE file](https://github.com/apache/incubator-openwhisk-catalog/pull/266)
    - Issue [#79 - Review NOTICE file for incubator-openwhisk-catalog](https://github.com/apache/incubator-openwhisk-release/issues/79)
- PR [#270 - Add the licenses of dependencies into LICENSE file](https://github.com/apache/incubator-openwhisk-catalog/pull/270)
- PR [#271 - Fix .md files to pass scanCode.py and comply with policy](https://github.com/apache/incubator-openwhisk-catalog/pull/271)
- PR [#272 - Remove the unnecessary dependencies](https://github.com/apache/incubator-openwhisk-catalog/pull/272)
- PR [#273 - Add ASF license headers to all Scala .conf files](https://github.com/apache/incubator-openwhisk-catalog/pull/273)
- PR [#274 - Fix markdown files with a typo. in the Hash license header.](https://github.com/apache/incubator-openwhisk-catalog/pull/274)
- PR [#275 - Restore the LICENSE and NOTICE to fit the source code release](https://github.com/apache/incubator-openwhisk-catalog/pull/275)
- PR [#277 - Add ASF license header to travis yaml file.](https://github.com/apache/incubator-openwhisk-catalog/pull/277)
- PR [#278 - Add ASF license header to .gradle files](https://github.com/apache/incubator-openwhisk-catalog/pull/278)
- PR [#279 - Update Travis to use ASF-Release.cfg](https://github.com/apache/incubator-openwhisk-catalog/pull/279)
- PR [#280 - Add the DISCLAIMER file for Apache incubator project](https://github.com/apache/incubator-openwhisk-catalog/pull/280)

**Other Issues**:
- Issue [#177 - create Invoke.py](https://github.com/apache/incubator-openwhisk-catalog/pull/177) - (pdesai) - Old open issue; Rodric requested changes on 2017-02-13).  It indicates "Adding a sample in python showing how to invoke another action "whisk.system/utils/date", closing issue #171"

**Comment by daisy-ycguo** [comment]
An issue is opened to track the license header issue: https://github.com/apache/incubator-openwhisk-catalog/issues/256. It is in opening status.

**Comment by daisy-ycguo** [comment]
A PR has been merged https://github.com/apache/incubator-openwhisk-catalog/pull/262 to fix this issue.

**Comment by mrutkows** [comment]
merged PR [270 - Add the licenses of dependencies into LICENSE file](https://github.com/apache/incubator-openwhisk-catalog/pull/270/files)

**Comment by mrutkows** [comment]
No open issues to track any longer

**Comment by houshengbo** [comment]
We can close this issue, since all the PRs are merged. The old open issue is no longer valid, since we decided to not add invoke action in other programming language.
