### ISSUE TITLE
Track LICENSE and NOTICE issues for `incubator-openwhisk-cli`

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-release#97]
Please use this issue to track any issues surrounding either the [LICENSE.txt](https://github.com/apache/incubator-openwhisk-cli/blob/master/LICENSE.txt) or [NOTICE.txt](https://github.com/apache/incubator-openwhisk-cli/blob/master/NOTICE.txt) file for the associated repository listed in the title.

**Open Issues/PRs**:
- _None_

**Closed Issues/Merged PRs**:
- PR [#265 -update notice file ](https://github.com/apache/incubator-openwhisk-cli/pull/265)
    - Issue [#76 - Review NOTICE file for incubator-openwhisk-cli](https://github.com/apache/incubator-openwhisk-release/issues/76)
- PR [#271 - Add the licenses of the dependencies into LICENSE](https://github.com/apache/incubator-openwhisk-cli/pull/271)
- PR [#283 - Add license header to 4 files](https://github.com/apache/incubator-openwhisk-cli/pull/283) - Fixed last 4 fils in #222 list (the 4 non-"test" files).
- PR [#285 - Add license headers](https://github.com/apache/incubator-openwhisk-cli/pull/235) - fixed Travis, CONTRIBUTING and README markdown.
- Issue [#222 - A list of source files missing Apache license headers](https://github.com/apache/incubator-openwhisk-cli/issues/222)
    -  "tests" .js files all moved to main OW repo. so James closed this issue with consent.
- PR [#305 - Add ASF license header to .gradle files](https://github.com/apache/incubator-openwhisk-cli/pull/305)
- PR [#308 - Update Travis to use ASF-Release.cfg](https://github.com/apache/incubator-openwhisk-cli/pull/308)
- PR [#312 - Add the DISCLAIMER file for Apache incubator project](https://github.com/apache/incubator-openwhisk-cli/pull/312)

**Comment by daisy-ycguo** [comment]
An issue is opened to track the header issue: https://github.com/apache/incubator-openwhisk-cli/issues/222

**Comment by daisy-ycguo** [comment]
A PR https://github.com/apache/incubator-openwhisk-cli/pull/283 is created. After this PR is merged, all files are with headers except the exclusions defined in Markdown file.

**Comment by mrutkows** [comment]
PR https://github.com/apache/incubator-openwhisk-cli/pull/271#pullrequestreview-116107376 has been merged.  Now we need to confirm the "template" of our project LICENSE file and update if necessary.

**Comment by mrutkows** [comment]
@daisy-ycguo  PR https://github.com/apache/incubator-openwhisk-cli/pull/283 has been merged however, the "test" files may still need licenses as they are not Performance impacted.  Therefore I have re-opened issue https://github.com/apache/incubator-openwhisk-cli/issues/222

**Comment by houshengbo** [comment]
We can close this issue since all PRs have been merged.
