### ISSUE TITLE
Track LICENSE and NOTICE issues for `incubator-openwhisk-client-go`

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-release#98]
Please use this issue to track any issues surrounding either the [LICENSE.txt](https://github.com/apache/incubator-openwhisk-client-go/blob/master/LICENSE.txt) or [NOTICE.txt](https://github.com/apache/incubator-openwhisk-client-go/blob/master/NOTICE.txt) file for the associated repository listed in the title.

**Open Issues/PRs**:
- _None_

**Closed Issues/Merged PRs**:
- PR [#65 - Add the NOTICE file for further development](https://github.com/apache/incubator-openwhisk-client-go/pull/65)
- PR [#66 - Add license headers](https://github.com/apache/incubator-openwhisk-client-go/pull/66)
- PR [#74 - Update notice file](https://github.com/apache/incubator-openwhisk-client-go/pull/74/files)
    - Issue [#77 - Review NOTICE file for incubator-openwhisk-client-go](https://github.com/apache/incubator-openwhisk-release/issues/77)
- PR [#75 -  Add the licenses of the dependencies into LICENSE](https://github.com/apache/incubator-openwhisk-client-go/pull/75)
- PR [#76 - Add scancode using ASF config. to Travis build](https://github.com/apache/incubator-openwhisk-client-go/pull/76)
- PR [#79 - Add license header to Makefile](https://github.com/apache/incubator-openwhisk-client-go/pull/79)
- PR [#81 - Update .md files to pass scancode with latest .cfg](https://github.com/apache/incubator-openwhisk-client-go/pull/81)
- PR [#83 - Fix markdown files with a typo. in the Hash license header](https://github.com/apache/incubator-openwhisk-client-go/pull/83)
- PR [#85 - Fix Makefile to use latest Hash ASF license header.](https://github.com/apache/incubator-openwhisk-client-go/pull/85)
- PR [#86 - Remove the disclaimer and the reference as experimental](https://github.com/apache/incubator-openwhisk-client-go/pull/86#pullrequestreview-121205648)
    - Issue [#82 - Change README to remove Disclaimer and "experimental" descriptions](https://github.com/apache/incubator-openwhisk-client-go/issues/82)
    - Issue [#48 - Update doc to remove experimental references](https://github.com/apache/incubator-openwhisk-client-go/issues/48)
- PR [#92 - Update Travis to use ASF-Release.cfg](https://github.com/apache/incubator-openwhisk-client-go/pull/92)
- PR [#93- Add the DISCLAIMER file for Apache incubator project](https://github.com/apache/incubator-openwhisk-client-go/pull/93#pullrequestreview-126509183)

**Comment by mrutkows** [comment]
As per discussion in issue: https://github.com/apache/incubator-openwhisk-release/issues/94

@daisy-ycguo @houshengbo we have need to document that we have decided not to include the generated "i18n_resources.go" file and are unable to add a header comment to its source input file (i.e., en_US.all.json or other similar language/country coded JSON files).  

IMO, we should include this decision/logic in this repo's LICENSE file.

**Comment by daisy-ycguo** [comment]
An issue is created to track the header issue: https://github.com/apache/incubator-openwhisk-client-go/issues/68

**Comment by daisy-ycguo** [comment]
A PR https://github.com/apache/incubator-openwhisk-client-go/pull/79 is created. After this PR is merged, all files are with headers except the exclusions defined in Markdown file.

**Comment by houshengbo** [comment]
We can close this issue, since all the PRs have been merged.
