### ISSUE TITLE
Track LICENSE and NOTICE issues for `incubator-openwhisk-runtime-nodejs`

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-release#99]
Please use this issue to track any issues surrounding either the [LICENSE.txt](https://github.com/apache/incubator-openwhisk-runtime-nodejs/blob/master/LICENSE.txt) or [NOTICE.txt](https://github.com/apache/incubator-openwhisk-runtime-nodejs/blob/master/NOTICE.txt) file for the associated repository listed in the title.

**Open Issues/PRs**:
- _None_

**Closed Issues/Merged PRs**:
- PR [#34 - Update NOTICE file](https://github.com/apache/incubator-openwhisk-runtime-nodejs/pull/34)
    - Issue [#82 - Review NOTICE file for incubator-openwhisk-runtime-nodejs](https://github.com/apache/incubator-openwhisk-release/issues/82)
- PR [#37 - Add license headers](https://github.com/apache/incubator-openwhisk-runtime-nodejs/pull/37)
- PR [#38 - Add the licenses of the dependencies into LICENSE](https://github.com/apache/incubator-openwhisk-runtime-nodejs/pull/38)
- PR [#39 - Add scancode to Travis using the ASF Release configuration.](https://github.com/apache/incubator-openwhisk-runtime-nodejs/pull/39)
- PR [#47 - Update .md and .sh files to pass scancode with latest .cfg](https://github.com/apache/incubator-openwhisk-runtime-nodejs/pull/47)
- PR [#48 - Add ASF license headers to all Scala .conf files.](https://github.com/apache/incubator-openwhisk-runtime-nodejs/pull/48)
- [#54 -Last files to need ASF License headers.](https://github.com/apache/incubator-openwhisk-runtime-nodejs/pull/54)
- PR [#55 - Fix bad Dockerfile license and use ASF release config](https://github.com/apache/incubator-openwhisk-runtime-nodejs/pull/55)
- [#25 - Some source files miss Apache license headers](https://github.com/apache/incubator-openwhisk-runtime-nodejs/issues/25)
    - Close issue (as completed)?

**Comment by daisy-ycguo** [comment]
An issue is created to track the header issue: https://github.com/apache/incubator-openwhisk-runtime-nodejs/issues/25

**Comment by daisy-ycguo** [comment]
I suggest to exclude below files from header scanning because they are config files with few creativity.

```
  openwhisk-runtime-nodejs/tests/src/test/resources/application.conf
  openwhisk-runtime-nodejs/ansible/environments/local/group_vars/all
  openwhisk-runtime-nodejs/ansible/environments/local/hosts
```

**Comment by daisy-ycguo** [comment]
A PR https://github.com/apache/incubator-openwhisk-runtime-nodejs/pull/37 to add license header is merged.

**Comment by mrutkows** [comment]
@daisy-ycguo merged https://github.com/apache/incubator-openwhisk-runtime-nodejs/pull/37
